Repository AOW-GroupProject/AgeOfWolves, pull requests merged in 2024-10, with the labels that each got.

#76 Feat: Wolf 함수 분리
  Config/DefaultGameplayTags.ini
  Content/Blueprints/02_AbilitySystem/02_Monster/GA_MonsterBasicAttack_1.uasset
  Content/Blueprints/02_AbilitySystem/02_Monster/GA_MonsterDashAttack.uasset
  Content/Blueprints/02_AbilitySystem/02_Monster/GA_MonsterDodge.uasset
  Content/Blueprints/02_AbilitySystem/02_Monster/GA_MonsterDodge_Back.uasset
  Content/Blueprints/02_AbilitySystem/02_Monster/GA_MonsterDodge_Left.uasset
  Content/Blueprints/10_Monster/BPBase_SplineMonster.uasset
  Content/Blueprints/10_Monster/MonsterData.uasset
  Content/Blueprints/10_Monster/Notify/AN_SetNextComboAttack.uasset
  Content/Blueprints/10_Monster/Wolf/BP_Wolf.uasset
  Content/Blueprints/10_Monster/Wolf/BT/BT_Wolf.uasset
  Content/Blueprints/10_Monster/Wolf/BT/Service/BTService_PrintKey.uasset
  Content/Blueprints/10_Monster/Wolf/BT/Task/BTTask_MoveToPlayerAndSetBBKey.uasset
  Content/Blueprints/10_Monster/Wolf/Notify/AN_AttackDamage.uasset
  Content/Blueprints/10_Monster/Wolf/Notify/AN_DashDamage.uasset
  Content/Blueprints/10_Monster/Wolf/Notify/AN_SetNextComboAttack.uasset
  Content/TempAsset/Enemy_Bear/Enemy_Bear_Animations/Wolf_BasicAttack_1.uasset
  Content/TempAsset/Enemy_Bear/Enemy_Bear_Animations/Wolf_BasicAttack_2.uasset
  Content/TempAsset/Enemy_Bear/Enemy_Bear_Animations/Wolf_DashAttack.uasset
  Content/TempAsset/Enemy_Bear/Enemy_Bear_Animations/Wolf_Dodge.uasset
  Saved/Config/CrashReportClient/UECC-Windows-062FF8BE49717BF72C5912A5EF12CC1B/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-171E13764A18E0A787E957A22F6095C2/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-32D61FE8491E24214D6DF0B796526D7F/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-3349129A418D463DB24F2E908B252D87/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-B3C5A6884701EF8B95F4B9B059162B5E/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-B52547E14149D16EF8ECBD9DE47CCDDC/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-BFFA725E4EED741275186490E1D31675/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-CE60923541D663B0D69F7E9FD41307DA/CrashReportClient.ini
  Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini
  Saved/Config/WindowsEditor/Game.ini
  Saved/Config/WindowsEditor/GameplayTagsEditorState.ini
  Saved/Config/WindowsEditor/Input.ini
  Source/AgeOfWolves/01_Character/BaseMonster.h
  Source/AgeOfWolves/02_AbilitySystem/03_ExecutionCalculation/ExecCalc_Damage.cpp
  Source/AgeOfWolves/10_Monster/BaseMonsterAIController.cpp
  Source/AgeOfWolves/10_Monster/BaseMonsterAS.cpp
  Source/AgeOfWolves/10_Monster/BaseMonsterAS.h
  Source/AgeOfWolves/10_Monster/BaseMonsterAttributeSet.cpp
  Source/AgeOfWolves/10_Monster/BaseMonsterAttributeSet.h
Labels: enhancement

#81 Fix: Inventory UI의 아이템 슬롯 메뉴와 확정 메뉴 최적화
  Content/Blueprints/08_UI/01_AkaOni/01_HUD/WBP_QuickSlot.uasset
  Content/Blueprints/08_UI/01_AkaOni/02_Menu/01_Inventory/02_ItemSlots/01_DropDownMenu/WBP_ItemSlot_DropDownMenu.uasset
  Content/Blueprints/08_UI/01_AkaOni/02_Menu/01_Inventory/02_ItemSlots/WBP_InventoryUI_ItemSlot.uasset
  Content/Blueprints/08_UI/01_AkaOni/02_Menu/01_Inventory/02_ItemSlots/WBP_ItemSlot_DropDownMenu.uasset
  Content/Blueprints/08_UI/01_AkaOni/02_Menu/01_Inventory/02_ItemSlots/WBP_ItemSlot_DropDownMenuOption.uasset
  Content/Blueprints/08_UI/01_AkaOni/02_Menu/01_Inventory/02_ItemSlots/WBP_ItemSlot_DropDownMenuOptionButton.uasset
  Content/Blueprints/08_UI/01_AkaOni/02_Menu/01_Inventory/02_ItemSlots/WBP_ItemSlots.uasset
  Saved/Config/CrashReportClient/UECC-Windows-221DD04741199899B80C42B38AA68B5E/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-406F024B4F1669C096B74AA04DA749E0/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-92A57AEC4FCC996BEECB0FB2C6AB3497/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-BF64705C48B263F4B35462AE12B3AD0B/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-E22E588C4B378791FAEAA987C35D9495/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-F6F016FB42EE11E488C8B185CCC6A196/CrashReportClient.ini
  Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini
  Source/AgeOfWolves/08_UI/02_Menu/01_InventoryUI/ItemSlots.cpp
  Source/AgeOfWolves/08_UI/02_Menu/01_InventoryUI/ItemSlots.h
  Source/AgeOfWolves/08_UI/ConfirmationMenu.cpp
  Source/AgeOfWolves/08_UI/ConfirmationMenu.h
  Source/AgeOfWolves/08_UI/DropDownMenu.h
  Source/AgeOfWolves/08_UI/InteractableItemSlot.h
  Source/AgeOfWolves/08_UI/ItemSlot.h
Labels: bug, enhancement

#83 Refactoring: GAS 리팩토링
  Content/Blueprints/01_Character/01_AkaOni/AnimationBlueprints/AnimationNotify/ANS_GetNextComboInput.uasset
  Content/Blueprints/01_Character/01_AkaOni/AnimationBlueprints/AnimationNotify/ANS_SkipComboMontage.uasset
  Saved/Config/WindowsEditor/Game.ini
  Source/AgeOfWolves/01_Character/PlayerCharacter.cpp
  Source/AgeOfWolves/02_AbilitySystem/02_GamePlayAbility/BaseGameplayAbility.cpp
  Source/AgeOfWolves/02_AbilitySystem/02_GamePlayAbility/BaseGameplayAbility.h
  Source/AgeOfWolves/03_Player/BasePlayerController.cpp
  Source/AgeOfWolves/04_Component/BaseAbilitySystemComponent.cpp
  Source/AgeOfWolves/04_Component/BaseAbilitySystemComponent.h
  Source/AgeOfWolves/04_Component/BaseInputComponent.cpp
  Source/AgeOfWolves/04_Component/BaseInputComponent.h
  Source/AgeOfWolves/04_Component/MonsterAbilitySystemComponent.cpp
  Source/AgeOfWolves/04_Component/MonsterAbilitySystemComponent.h
  Source/AgeOfWolves/04_Component/PlayerAbilitySystemComponent.cpp
  Source/AgeOfWolves/04_Component/PlayerAbilitySystemComponent.h
  Source/AgeOfWolves/10_Monster/BaseMonsterASC.cpp
Labels: enhancement

#88 feat: 데미지 전달 확인
  Config/DefaultEngine.ini
  Content/Blueprints/02_AbilitySystem/02_Monster/AS_Wolf.uasset
  Content/Blueprints/02_AbilitySystem/02_Monster/GA_MonsterDashAttack.uasset
  Content/Blueprints/10_Monster/MonsterData.uasset
  Content/Blueprints/10_Monster/Wolf/BP_Wolf.uasset
  Content/Blueprints/10_Monster/Wolf/GE_InitMonsterAttributeTemp.uasset
  Content/Blueprints/10_Monster/Wolf/Notify/AN_AttackDamage.uasset
  Content/Blueprints/10_Monster/Wolf/Notify/AN_DashDamage.uasset
  Content/TempAsset/Enemy_Bear/Enemy_Bear_Animations/Wolf_BasicAttack_2.uasset
  Content/TempAsset/Enemy_Bear/Enemy_Bear_Animations/Wolf_BasicAttack_3.uasset
  Saved/Config/CrashReportClient/UECC-Windows-435F995345BF4214E8B08B82D992A92C/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-458A683D4163E82F1771988ED486D7A0/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-55A746534E4A61B08E9975A50A1A4144/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-A47AE48D415BE471BAA763B716F15E26/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-AD75BECA44B399834BF9BEBF76EEFEFF/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-D4F43F04416F4619285301A99E1F59BC/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-D538960B4CCD5BDA26E9BA924314E15B/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-DBC2ED434246D6C1ABF5609A7F861F1B/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-E0E8C8BC4AD30D80D7DC1EB1E10A5D9D/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-E561A9234E92C708A5243E9054B6EA84/CrashReportClient.ini
  Saved/Config/WindowsEditor/Editor.ini
  Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini
  Saved/Config/WindowsEditor/Game.ini
  Saved/Config/WindowsEditor/Input.ini
  Source/AgeOfWolves/01_Character/BaseMonster.cpp
  Source/AgeOfWolves/01_Character/BaseMonster.h
Labels: bug, enhancement

#93 Fix: Inventory UI 기능 추가 업데이트
  .vsconfig
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IMC_AkaOni_OnGround.uasset
  Saved/Config/CrashReportClient/UECC-Windows-7AFDAF024DDB948FD8AD5989B5AE10D4/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-B4B651E24B969006E06F3489BA2F4428/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-D2EBC7304944628E74E730949B70E42C/CrashReportClient.ini
  Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini
  Source/AgeOfWolves/08_UI/02_Menu/01_InventoryUI/InventoryUIContent.cpp
  Source/AgeOfWolves/08_UI/02_Menu/01_InventoryUI/InventoryUIContent.h
  Source/AgeOfWolves/08_UI/02_Menu/01_InventoryUI/ItemSlots.cpp
  Source/AgeOfWolves/08_UI/02_Menu/01_InventoryUI/ItemSlots.h
Labels: bug, wontfix

#87 Feature: Hit React 추가#85
  Content/Blueprints/01_Character/01_AkaOni/AnimationBlueprints/AnimationMontage/AM_HitReact.uasset
  Content/Blueprints/01_Character/01_AkaOni/AnimationBlueprints/AnimationMontage/AM_red_oni_dodge.uasset
  Content/Blueprints/02_AbilitySystem/01_Character/01_AkaOni/AS_AkaOni.uasset
  Content/Blueprints/02_AbilitySystem/01_Character/01_AkaOni/HitReact/GA_PlayerHitReact.uasset
  Content/Blueprints/02_AbilitySystem/01_Character/01_AkaOni/HitReact/GE_HitReact.uasset
  Content/Blueprints/03_Player/BP_DefaultPlayerController.uasset
  Saved/Config/WindowsEditor/GameplayTagsEditorState.ini
  Source/AgeOfWolves/02_AbilitySystem/01_AttributeSet/BaseAttributeSet.cpp
  Source/AgeOfWolves/02_AbilitySystem/AOWGameplayTags.cpp
  Source/AgeOfWolves/02_AbilitySystem/AOWGameplayTags.h
Labels: enhancement

#97 Fix: ATRM 내부 Gameplay Tag Container 관리 방법 변경
  Content/Blueprints/02_AbilitySystem/01_Character/01_AkaOni/ATRM_AkaOni.uasset
  Saved/Config/CrashReportClient/UECC-Windows-190041F447665221DB839A9CC3409B4B/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-2325F5EB4C67212FB743F38043DE2E63/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-31A7240846B695A0BEA1ACBB7FCD7E2A/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-8366876C4F6CC6D5FE03D8998EFC00F0/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-93D1B88C474C7F085CBDBFB5FDB72F75/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-B781F9FB46022CEEE6040BB0E12AF884/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-CA010E1E4BC943AEDF4D1DBC541B215C/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-F1C59F0B416549BCA6D1C188CF72E6DC/CrashReportClient.ini
  Saved/Config/WindowsEditor/Editor.ini
  Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini
  Saved/Config/WindowsEditor/GameplayTagsEditorState.ini
  Source/AgeOfWolves/02_AbilitySystem/AbilityTagRelationshipMapping.cpp
  Source/AgeOfWolves/02_AbilitySystem/AbilityTagRelationshipMapping.h
  Source/AgeOfWolves/04_Component/BaseAbilitySystemComponent.cpp
  Source/AgeOfWolves/04_Component/BaseAbilitySystemComponent.h
Labels: bug, enhancement

#99 Feature: CombatInterface 제작
  Saved/Config/ConsoleHistory.ini
  Saved/Config/CrashReportClient/UECC-Windows-18651C7A481DD79C47CE65840DE53992/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-359CD6DE49AC1E53C1B39B898335DC3B/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-4555EA354EB90B2912190BAF313CE5D9/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-4B4020C94F5EA06552F91987750B1016/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-51F6E1E247886ECF57C91D94FBB9F01A/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-58828D7E4CBCB8E3076250893BD097E2/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-668AB273420D6DA8F5E67CB150DEE338/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-73AF03F54AA3BDC2755D8080C594B5E7/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-7D34DFED469F2B407991F5AE4C3C41E9/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-87FA8B0744659A783AACAC96F0755FE1/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-8D79862E4698CF58B89A998F6836C2C9/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-94F1F99D44B659825C5C23A98B9C4F1D/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-97E139684BE495068364228045661460/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-9A5451514762DBA99B5FA088AFBD3AFA/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-9D4F36614BF74EF9C755F0846138F3F7/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-A111E36546FC4D249E7878A30DD628F7/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-B359B18B457051CA7DE3D693E6A13939/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-BA9BE915460088DDF5788D9696DA4B6F/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-BB77B78646E9E8231E301C935C1DBF53/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-C09079784BF9D57F651EE7A92D20A149/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-C7CD2D8C45BAB4C4956A1480247A0D5E/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-C92092B4430B9B26413DD3B180F60B88/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-E10751EB47C73EF6DA422792544CEDE7/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-E30C256B4B20A0D76BFEB7906F6A572C/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-EC493F42494263C63377FA92D754FE0D/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-ED3D42784723E51A031559B74C84CC17/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-F03A677648A1EA8C95A145A72784D386/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-F053546D4836C46462D3998ADA216901/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-FE08AD074332168F2E9BA3A5D946514A/CrashReportClient.ini
  Saved/Config/CrashReportClient/UECC-Windows-FFFB306449E432A6621440992E00907A/CrashReportClient.ini
  Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini
  Saved/Config/WindowsEditor/Game.ini
  Saved/Config/WindowsEditor/Input.ini
  Source/AgeOfWolves/01_Character/CombatInterface.cpp
  Source/AgeOfWolves/01_Character/CombatInterface.h
  Source/AgeOfWolves/01_Character/PlayerCharacter.cpp
  Source/AgeOfWolves/01_Character/PlayerCharacter.h
  Source/AgeOfWolves/02_AbilitySystem/01_AttributeSet/BaseAttributeSet.cpp
Labels: enhancement
