Repository AOW-GroupProject/AgeOfWolves, pull requests merged in 2025-09, with the labels that each got.

#343 Feature interaction structure#318
  Config/DefaultGameplayTags.ini
  Content/Assets/AgeOfWolves/06_Map/Evrionment/Asset/Wolf_statue/wolf_statue.uasset
  Content/Assets/AgeOfWolves/06_Map/LV_Map.umap
  Content/Blueprints/02_AbilitySystem/01_Player/10_Interaction/02_Structure/GE_AkaOni_Structure.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/10_Interaction/02_Structure/IGA_AkaOni_Structure.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/AS_AkaOni.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/ATRM_AkaOni.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IA_Interaction.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IC_AkaOni_OnGround.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IMC_AkaOni_OnGround.uasset
  Content/Blueprints/13_Structure/BP_StructureTest.uasset
  Content/StarterContent/Audio/Collapse01.uasset
  Content/StarterContent/Blueprints/Blueprint_CeilingLight.uasset
  Source/AgeOfWolves/02_AbilitySystem/06_AbilityTask/AT_MoveToInteractionZone.cpp
  Source/AgeOfWolves/04_Component/InteractionComponent.cpp
  Source/AgeOfWolves/04_Component/InteractionComponent.h
  Source/AgeOfWolves/04_Component/ObjectiveDetectionComponent.cpp
  Source/AgeOfWolves/04_Component/ObjectiveDetectionComponent.h
  Source/AgeOfWolves/16_Level/Area.cpp
  Source/AgeOfWolves/16_Level/Area.h
  Source/AgeOfWolves/18_Structure/StructureBase.cpp
  Source/AgeOfWolves/18_Structure/StructureBase.h
  Source/AgeOfWolves/19_Interface/InteractionInterface.cpp
  Source/AgeOfWolves/19_Interface/InteractionInterface.h
Labels: enhancement

#346 🔥Fix: BT(Type1) 수정 및 발도 장착/해제 어빌리티 수정
  Config/DefaultGameplayTags.ini
  Content/Assets/AgeOfWolves/06_Map/LV_AOW.umap
  Content/Blueprints/01_Character/01_AkaOni/AnimationBlueprints/ABP_AkaOni_BaseLayer.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/01_Attack/03_Battoujutsu/00_Battoujutsu_1/CGA_AkaOni_Battoujutsu_1.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/00_AnimMontage/Frank_RPG_Katana_Stance1_to_3_Montage.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/00_AnimMontage/Frank_RPG_Katana_Stance1_to_3_Montage_1.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/00_AnimMontage/Frank_RPG_Katana_Stance3_to_1_Montage_2.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/01_BattouEquip/GA_AkaOni_BattouEquip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/01_BattouEquip/GE_Apply_ChangeBattouCombatToNormalCombat.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/01_BattouEquip/GE_Apply_ChangeCombatStateToBattouCombat.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/01_BattouEquip/GE_Cost_CanBttouEquip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/02_BattouUnequip/GA_AkaOni_BattouUnequip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/02_BattouUnequip/GE_Apply_ChangeBattouCombatToNormalCombat.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/02_BattouUnequip/GE_Cost_CanBattouUnequip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/GA_BattouEquipOrUnequip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/GE_Apply_ChangeCombatStateToSpecialCombat.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/02_BattouEquipAndUnequip/GE_Cost_CanBttouEquip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/03_GuardEquipAndUnequip/01_GuardEquip/GA_GuardEquip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/06_EquipAndUnequip/03_GuardEquipAndUnequip/02_GuardUnequip/GA_AkaOni_GuardUnequip.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/AS_AkaOni.uasset
  Content/Blueprints/02_AbilitySystem/01_Player/ATRM_AkaOni.uasset
  Content/Blueprints/02_AbilitySystem/02_SamuraiAI/06_EquipAndUnequip/02_BattouEquipAndUnequip/00_AnimMontage/Frank_RPG_Katana_Stance1_to_3_Montage.uasset
  Content/Blueprints/02_AbilitySystem/02_SamuraiAI/06_EquipAndUnequip/02_BattouEquipAndUnequip/GA_BattouEquipOrUnequip.uasset
  Content/Blueprints/02_AbilitySystem/04_Ninja/06_EquipAndUnequip/02_BattouEquipAndUnequip/00_AnimMontage/Frank_RPG_Katana_Stance1_to_3_Montage.uasset
  Content/Blueprints/02_AbilitySystem/04_Ninja/06_EquipAndUnequip/02_BattouEquipAndUnequip/GA_BattouEquipOrUnequip.uasset
  Content/Blueprints/04_AI/02_Ninja/BT_Ninja.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IA_BattouEquip.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IA_BattouEquipOrUnequip.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IA_BattouUnequip.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IA_GuardEquip.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IA_GuardEquipOrUnequip.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IC_AkaOni_OnGround.uasset
  Content/Blueprints/06_Input/Aka_Oni/OnGround/IMC_AkaOni_OnGround.uasset
  Content/StarterContent/Architecture/Floor_400x400.uasset
  Content/StarterContent/Blueprints/Blueprint_CeilingLight.uasset
  Content/__ExternalActors__/Blueprints/Level/02_Level_CombatTest_AllEnemy/7/YP/PD6HIPV0UAEN42XB2ZGWPQ.uasset
  Source/AgeOfWolves/02_AbilitySystem/05_ApplicationRequirement/AR_CheckIsBattouCombat.cpp
  Source/AgeOfWolves/02_AbilitySystem/05_ApplicationRequirement/AR_CheckIsBattouCombat.h
  Source/AgeOfWolves/04_Component/AIAbilitySequencerComponent.cpp
  Source/AgeOfWolves/04_Component/AIAbilitySequencerComponent.h
  Source/AgeOfWolves/04_Component/BaseInputComponent.cpp
  Source/AgeOfWolves/04_Component/BaseInputComponent.h
  Source/AgeOfWolves/04_Component/DynamicCameraComponent.cpp
  Source/AgeOfWolves/04_Component/DynamicCameraComponent.h
  Source/AgeOfWolves/05_Animation/BaseAnimInstance.cpp
  Source/AgeOfWolves/05_Animation/BaseAnimInstance.h
  Source/AgeOfWolves/10_AI/BaseAIController.h
  Source/AgeOfWolves/11_BTTask/BTTask_FinishReadyForCombat.cpp
  Source/AgeOfWolves/11_BTTask/BTTask_FinishReadyForCombat.h
  Source/AgeOfWolves/11_BTTask/BTTask_ReadyForCombat.cpp
  Source/AgeOfWolves/11_BTTask/BTTask_ReadyForCombat.h
  Source/AgeOfWolves/11_BTTask/BTTask_TryCombatLoop.cpp
  Source/AgeOfWolves/12_BTService/BTService_SelectNearestLocation.cpp
  Source/AgeOfWolves/12_BTService/BTService_SelectNearestLocation.h
Labels: bug, enhancement

#352 Refact 늑대상호작용 어빌리티 수정
  Content/Assets/AgeOfWolves/06_Map/LV_AOW.umap
  Content/Assets/AgeOfWolves/06_Map/LV_Map.umap
  Content/Blueprints/02_AbilitySystem/01_Player/10_Interaction/02_Structure/IGA_AkaOni_Structure.uasset
  Content/Blueprints/03_Player/BP_DefaultPlayerController.uasset
  Source/AgeOfWolves/02_AbilitySystem/06_AbilityTask/AT_MoveToInteractionZone.cpp
  Source/AgeOfWolves/02_AbilitySystem/06_AbilityTask/AT_MoveToInteractionZone.h
Labels: enhancement

#372 Refact: 다이내믹 카메라 시스템 3차 수정
  Source/AgeOfWolves/04_Component/DynamicCameraComponent.cpp
  Source/AgeOfWolves/04_Component/DynamicCameraComponent.h
  Source/AgeOfWolves/16_Level/Area.cpp
Labels: enhancement, wontfix
